### ISSUE TITLE
Scrolls are incorrectly detected/mapped with 1.1.0

### ISSUE THREAD

**Issue by el0c** [Siphalor/amecs#1]
Scrolling up with the latest build of Amecs binds the key to scroll down, and vice versa. 

Tested with only Amecs (1.1.0+1.14.3) and Fabric API (0.3.0+build.187), as well as with multiple mice; a G703 and a Basic Mircosoft mouse.

**Comment by Siphalor** [comment]
This should be fixed in 1.1.1
