### ISSUE TITLE
[Curseforge Page] Notify about Autojump and Skin hotkeys

### ISSUE THREAD

**Issue by IdrisQe** [Siphalor/amecs#10]
If there's one thing I can't stand (among many other things), it's when a mod doesn't explain its content properly. Due to a bug thanks to Informed Load, I wasn't aware the Autojump and Skin hotkeys even existed, and for some reason my Autojump kept turning itself on and off despite not knowing that I had any mod that added such a hotkey. Even if the keys had shown in my controls menu (thanks again, Informed Load), I wouldn't have known which mod added those. It's rather annoying.

**Comment by Siphalor** [comment]
Whoops, I announced that change to the Fabric community and totally forgot to change it on CF once it got approved.
I changed the description, thanks :)
