### ISSUE TITLE
Search by keybind

### ISSUE THREAD

**Issue by Madis0** [Siphalor/amecs#11]
The search bar is great for finding options to bind keys _for_, but what if you want to search what that key _already does_? 

One way to do it would be to just match the keys entered in the search box (like "w" for the option "Walk forwards" and the bound key W itself). However that would not work well with non-character keys, so I would instead suggest using a "keybind" button next to the search box, which would work as a filter as long as it is bound.

This is especially useful if the user is using lots of mods or a modpack. Or it is also good for finding duplicates.

**Comment by Madis0** [comment]
Oh, I see how you made it work - search by the name of the key. Pretty clever actually :slightly_smiling_face:

**Comment by Madis0** [comment]
Seems like this feature has broken in 1.15.2.

**Comment by Siphalor** [comment]
I'm gonna investigate that

**Comment by Siphalor** [comment]
Seems to work fine for me - Can you please try it again and if it still doesn't work open a new issue with steps to reproduce 🙂
