### ISSUE TITLE
Phrase "Auto Jump" is redundant

### ISSUE THREAD

**Issue by Madis0** [Siphalor/amecs#14]
The language file phrase
```
"amecs.toggled.auto_jump": "Auto Jump"
```
is redundant because vanilla already has
```
"options.autoJump": "Auto-Jump"
```
which you could reuse, because you are using it as a variable on `Enabled %s`/`Disabled %s` anyway.

**Comment by Siphalor** [comment]
Unsure about that one 🤔

**Comment by Siphalor** [comment]
I'll still keep it separated
