### ISSUE TITLE
Make narrator rebindable

### ISSUE THREAD

**Issue by Madis0** [Siphalor/amecs#17]
[The narrator](https://minecraft.gamepedia.com/Multiplayer#Narrator) hotkey is hardcoded to Ctrl+B, which kind of intervenes with the Amecs' auto-jump default key when running (holding Ctrl). 

Since Amecs supports hotkeys with modifiers, how about making the vanilla one rebindable? Would also "fix" the [bug 122645](https://bugs.mojang.com/browse/MC-122645) :)

**Comment by Madis0** [comment]
https://github.com/quat1024/RebindNarrator 
inspiration

**Comment by Siphalor** [comment]
Since RandomPatches also implements this, I'll say there's no reason to have this in Amecs as well.

**Comment by muzikbike** [comment]
RandomPatches hasn't been updated in over two years at this point, so could this be reopened?
