### ISSUE TITLE
doesnt save special controls to options.txt

### ISSUE THREAD

**Issue by RyanCR03** [Siphalor/amecs#19]
the mod doesn't save special controls to options.txt, so when you open the game for a second time the controls break... https://imgur.com/iDFuhyV.png

**Comment by Darwign** [comment]
same problem here if I close the game it doesn't save the special controls making you manually set the control options every time you launch the game

**Comment by Siphalor** [comment]
Do you by chance use optifine?
Then I've got your answer 🤔

**Comment by Darwign** [comment]
god fucking damit please don't say it

**Comment by Darwign** [comment]
does optifine has to go or is there a work around it ?

**Comment by Siphalor** [comment]
Currently it has to go for that; See Siphalor/amecs-api#1 for reference.

**Comment by Siphalor** [comment]
As there were no more reports I just declare this thing fixed.
Please respond if this reoccurs.
