### ISSUE TITLE
No searchbar in Amecs API

### ISSUE THREAD

**Issue by Madis0** [Siphalor/amecs#21]
I noticed that in Minecraft 1.16.1, the Amecs bundled with Mouse Wheelie is an API and now lacks a search bar. Is that intended? And if yes, what can I do to get it back - install full Amecs or something like [Controlling](https://www.curseforge.com/minecraft/mc-mods/controlling)?

Edit: oops, Controlling is a 1.15 Forge mod. So seems like no searchbar for 1.16.1 is possible :(
Edit 2: [Fabric Controlling](https://www.curseforge.com/minecraft/mc-mods/fabric-controlling) is also available and it works!
Edit 3: The updated Amecs works too, but the question is - is it intended to keep the API just an API now?

**Comment by Siphalor** [comment]
I don't know how I missed this but the plan is to keep only the most essential stuff in Amecs API.
Everything else is/will be in Amecs so end users have a better way to decide what features they want.

So if you want a scrollbar you can download Amecs additionally to Mouse Wheelie. That's the way that it's intended right now. :)
