### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Dhenier** [Siphalor/amecs#22]
The game crashed whilst initializing game
Error: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'client' provided by 'amecs'
[crash-2020-07-03_00.42.14-client.txt](https://github.com/Siphalor/amecs/files/4867827/crash-2020-07-03_00.42.14-client.txt)

**Comment by Siphalor** [comment]
I think this was an update issue? It should be fixed now for quite some time :)
