### ISSUE TITLE
warn in log

### ISSUE THREAD

**Issue by calloatti** [Siphalor/amecs#3]
I get this in the log file when using amecs-1.1.0+1.14.3.jar:

`[18:43:00] [main/WARN]: Injection warning: LVT in net/minecraft/class_312::method_1598(JDD)V has incompatible changes at opcode 100 in callback net/minecraft/class_312::handler$onMouseScroll$zef000.`

**Loader**
Minecraft 1.14.3
[Fabric Loader 0.4.8+build.155](https://fabricmc.net)

**Mods**
- [Amecs (Fabric): amecs-1.1.0+1.14.3.jar](https://www.curseforge.com/minecraft/mc-mods/amecs)
- [Autofish: Autofish-0.8.4-fabric-mc1.14.jar](https://www.curseforge.com/minecraft/mc-mods/autofish)
- [Illuminations | Fireflies and fairies: illuminations-0.3.0-1.14.3.jar](https://www.curseforge.com/minecraft/mc-mods/ladysnake-illuminations)
- [More Enchantments: MoEnchantments-1.5.8.jar](https://www.curseforge.com/minecraft/mc-mods/fabric-more-enchantments)
- [Mouse Wheelie (Fabric): mousewheelie-1.2.4+1.14.3.jar](https://www.curseforge.com/minecraft/mc-mods/mouse-wheelie)
- [Nbt Crafting (Fabric): nbtcrafting-1.2.1+1.14.3-pre2.jar](https://www.curseforge.com/minecraft/mc-mods/nbt-crafting)
- [Paper Doll: paperdoll-1.0.0.jar](https://www.curseforge.com/minecraft/mc-mods/paper-doll)
- [Press To Walk: presstowalk-1.0.2.jar](https://www.curseforge.com/minecraft/mc-mods/press-to-walk)
- [Resolution Control: resolution-control-1.0.0.jar](https://www.curseforge.com/minecraft/mc-mods/resolution-control)
- [Roughly Enough Items: RoughlyEnoughItems-2.9.6+build.135.jar](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items)
- [Stockpile: stockpile-1.0.8+1.14.3.jar](https://www.curseforge.com/minecraft/mc-mods/stockpile)
- [Trees Do Not Float: tdnf-1.2.0+build.25.jar](https://www.curseforge.com/minecraft/mc-mods/trees-do-not-float)

**APIs/LIBs**
- [Fabric API: fabric-api-0.3.0+build.188.jar](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
- [Fabric Language Kotlin: fabric-language-kotlin-1.3.40+build.1.jar](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)

**Comment by Siphalor** [comment]
Should be fixed now
