### ISSUE TITLE
Keys with default modifier keys unable to NOT have modifier keys

### ISSUE THREAD

**Issue by IdrisQe** [Siphalor/amecs#31]
Minecraft 1.16.5, tested with both AMECS 1.3.3 and with the AMECS embedded in Mouse Wheelie 1.6.4, BackSlot 1.1.9, RandomPatches 2.4.5
**_Also no I am not using Optifine._**

Keybinds with defaults involving modifier keys don't seem to be working correctly. Whenever I launch the game, they are reset to containing the modifier keys.
-The "Toggle Narrator" Keybind from RandomPatches, which is set to use AMECS if available, keeps getting reset to "Control+"
-The "Switch Belt Slot" Keybind from Backslot keeps resetting to its default "Shift+g"
-I tried changing them to " " (unbound) and "g" respectively, leading to these results.

The "Switch Back Slot" Keybind from Backslot, however, does not reset, despite also being set to use AMECS. The difference is that by default it is set to "g", no modifier key. Any other keybind also saves just fine.

Further testing:
-Removed RandomPatches, re-added it. Keybind was reset to "Control+b" as it should have been.
-Set RandomPatches Toggle Narrator keybind to "z" and BackSlot Belt Slot keybind to "u", neither key used currently.
-Relaunched game. Narrator key was now set to "Control+z" and Belt Slot keybind was now "Shift+u".

Since the modifiers aren't getting saved to options.txt, I don't understand why on earth they keep getting re-added. It should just be read from options.txt that the set keys are "z" and "u" and then be fine with it, shouldn't it?

**Comment by srnyx** [comment]
This also affects Toggle Sprint: https://github.com/Siphalor/mouse-wheelie/issues/111

**Comment by Siphalor** [comment]
Sorry for taking so long to fix this silly little thing.
You caught me on my university-enforced hiatus during february/march. And it took me a while to catch up :)
