### ISSUE TITLE
log spam on server

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Siphalor/amecs#56]
It's mostly harmless, but this is logged on servers
```
[19:54:21] [main/WARN]: @Mixin target net.minecraft.class_459$class_462 was not found amecs.mixins.json:ControlsListWidgetKeyBindingEntryAccessor from mod amecs
[19:54:21] [main/WARN]: Error loading class: net/minecraft/class_309 (java.lang.ClassNotFoundException: net/minecraft/class_309)
[19:54:21] [main/WARN]: @Mixin target net.minecraft.class_309 was not found amecs.mixins.json:MixinKeyboard from mod amecs
```
This could be fixed by moving all mixins to the `"client"` array in `amecs.mixins.json`.

Side note: `"environment"` in `fabric.mod.json` should be `"client"`, not `"*"`.

**Comment by Klotzi111** [comment]
> This could be fixed by moving all mixins to the "client" array in amecs.mixins.json.

> Side note: "environment" in fabric.mod.json should be "client", not "*".

Yes. Both is correct. Sadly that is "not nice" in this repo. (Fixed in my fork)
But on the other hand `amecs` is not required to have on the server anyways. It is a client only mod.

**Comment by supersaiyansubtlety** [comment]
Is your fork published?

I know it's a client mod, I only have it on my server because it makes maintaining my 'mod pack' easier.

**Comment by Klotzi111** [comment]
> Is your fork published?

Yes. [Here](https://github.com/Klotzi111/amecs)

**Comment by Klotzi111** [comment]
@Siphalor your referenced commit does only fix one of the problems that [supersaiyansubtlety](https://github.com/supersaiyansubtlety) mentioned.

> This could be fixed by moving all mixins to the "client" array in amecs.mixins.json.

This still needs to be done by moving all mixins from the `mixins` field to `client`

**Comment by Siphalor** [comment]
Actually, that doesn't matter.

When the environment doesn't match with the one that the game is loading in, Fabric will completely ignore the mod.
So the mixin configuration will be ignored on servers anyway.

**Comment by Klotzi111** [comment]
Yeah you are right. But it would be nicer
