### ISSUE TITLE
Ability to remove keybinds [Fabric - 1.18.2]

### ISSUE THREAD

**Issue by Shadowdragon019** [Siphalor/amecs#57]
# Why
Scrolling through a massive list of keybinds isn't fun, especially from a modpackers perspective.
From disabling content & it's keybind being useless, or those mods which add keybinds that are just raw bloat.

It's also easier to play with less keybinds, as the memorization & searching is decreased.

# Examples
### Useless
![image](https://user-images.githubusercontent.com/67480398/190840069-660ed185-0240-43d1-a88e-6cea34714dfc.png)
These 2 are effectively useless, you aren't going to use them often & the time they save is minimal. Especially when you're a player.
It's literally just:
> Escape -> Click

or
> Escape -> Click -> "mouse" -> Click -> Click

### Broken
![image](https://user-images.githubusercontent.com/67480398/190840479-e7b810c4-2ac5-4eff-abd0-4a95118e371a.png)
Due to mod incompatibilities these don't work everywhere, so I opt to just remove them

**Comment by Klotzi111** [comment]
I do not really get what you want. Do you want them unfunctional or not listed in the keybindings list?
If it is first. Just unbind them. If it is second. Use a mod (for example: Amecs, Controlling) that filters the keybindings shown.

If you want to make custom filters and keep that filter even after reopening the keybindings list. Than that would be a plausible feature request for Controlling. (Amecs has not really a focus on filtering keybindings)
