### ISSUE TITLE
Update to 1.20

### ISSUE THREAD

**Issue by Excellent62412** [Siphalor/amecs#67]
AMECS has taken over 3 months to update to 1.19.4 since it released, if possible i want developers to begin updates during pre releases, myself and certainly other people don't want to endure that inconsistency.

**Comment by Felix14-v2** [comment]
https://modrinth.com/mod/amecs/version/1.3.9+mc.1.20-pre2

**Comment by Felix14-v2** [comment]
Btw, @Siphalor, can you mark the 1.20 release as compatible with 1.20.1 on Modrinth? It just work without any [new] issues. Also, I don't think issues like this are still useful, maybe close them?

**Comment by Siphalor** [comment]
Done :)

Yeah, I originally forgot to close this issue after updating ^^
