### ISSUE TITLE
Make Amecs compatible with Controlling

### ISSUE THREAD

**Issue by MbtMarco** [Siphalor/amecs#73]
You could make Amecs compatible with Controlling. 
It would be great to use them together however Amecs functions do not work with Controlling.
https://modrinth.com/mod/controlling

**Comment by GamingInfinite** [comment]
#49 Someone linked their fork, and while its not to 1.20 yet, it is a working solution.
Besides the point this issue is a dupe and should be closed.

**Comment by MbtMarco** [comment]
However, it is not officially supported.

**Comment by Boobies** [comment]
Can't easily incorporate the solution into the main branch because that code has seen massive refactoring.
