### ISSUE TITLE
Incompatible with 19w42a

### ISSUE THREAD

**Issue by Thaumatarge** [Siphalor/amecs#8]
It appears that Amecs is broken when running with 19w42a. (Possibly due to changes in the settings (in relation to behaviour of sprinting and crouching))
[crash-2019-10-27_17.28.41-client.txt](https://github.com/Siphalor/amecs/files/3776123/crash-2019-10-27_17.28.41-client.txt)

**Comment by Siphalor** [comment]
Totally forgot about that issue - we're in the 1.15 pre-releases now xD
