### ISSUE TITLE
Add keybinds (macros)

### ISSUE THREAD

**Issue by Madis0** [Siphalor/amecs#9]
Amecs has various options for managing existing keybinds. How about letting users define new ones too? 

By that, I mean [implementing this mod](https://www.curseforge.com/minecraft/mc-mods/command-macros) into Amecs, with the difference that Amecs' feature would work inline on the key config screen, instead of a separate view. 

The keybinds would be categorized as "Amecs macros", last item in the category would be a wide button "Add a macro". 

The inline UI could look like this: 

[_Command_] [Delayed*] [_Delay time**_] [_Keybind_] [X]

`*` Delayed/Repeating/SingleUse/DisplayOnly 

`**` Shown only for "Delayed" and "Repeating"

**Comment by Siphalor** [comment]
What would be the benefit of having this implemented into Amecs (it's already available as a Fabric mod?).

**Comment by Madis0** [comment]
Consistent UX - all keybinds in one, searchable view.

**Comment by Siphalor** [comment]
I thought about this again and I think it is totally out of bounds for Amecs (a library mod with a few utility features)
